"""Write src/scm/lib/migrated-deliveries-not-invoiced.generated.ts: the delivery
orders carried over from AutoCount that AutoCount never invoiced, so the ERP may
invoice them like any other delivery (docs/bugs/0918).

WHY. A delivery order carried over from AutoCount was refused by every invoice
path on the premise that AutoCount had already invoiced it. On 2026-09-15 that
was true of 2 of the 122 migrated deliveries with no invoice in the ERP, and
false of 120: staff could not bill a delivered order, HC-DO-011484 among them.
Whether AutoCount invoiced a delivery lives only in the book (DocTransfer from
the DO's lines to an invoice), which the Worker cannot read, so the answer is
measured here and committed as a list.

WHAT COUNTS AS "NEVER INVOICED". The book holds the delivery under the number
the ERP mirrors, it has at least one line, and no line of it was transferred to
an invoice that is not cancelled. Anything else - a delivery the book does not
hold, one with any line invoiced, one with no AutoCount number - stays off the
list and stays refused.

INPUT. The JSON printed by list-migrated-deliveries.mjs (the ERP side).

READ-ONLY: SELECT only, NOLOCK, a 15-second timeout, batches of 80 documents.

RE-RUN: rewrites the generated file from the book as it is now. The file is
committed, so a change shows as a diff in review.

Usage:
  node scripts/list-migrated-deliveries.mjs > migrated-deliveries.json
  AC_CRED_FILE=<path> python scripts/export-migrated-deliveries-not-invoiced.py migrated-deliveries.json
"""
import json
import os
import re
import sys
from datetime import datetime, timezone

try:
    import pyodbc
except ImportError:
    sys.exit("pyodbc is required: pip install pyodbc")

HOST = os.environ.get("AC_HOST", "10.147.17.100,55500")
DB = os.environ.get("AC_DB", "AED_HOUZS")
USER = os.environ.get("AC_USER", "sa2")
DRIVER = os.environ.get("AC_DRIVER", "SQL Server Native Client 11.0")
CRED = os.environ.get("AC_CRED_FILE")
if not CRED or not os.path.exists(CRED):
    sys.exit("set AC_CRED_FILE to a file containing the AutoCount password")
if len(sys.argv) != 2:
    sys.exit("usage: export-migrated-deliveries-not-invoiced.py <list-migrated-deliveries output>")

erp = json.load(open(sys.argv[1], encoding="utf-8"))
deliveries = erp["deliveries"]
book_nos = sorted({d["book_no"] for d in deliveries if d.get("book_no")})

with open(CRED, encoding="utf-8") as fh:
    password = fh.read().strip()
cn = pyodbc.connect(
    "DRIVER={%s};SERVER=%s;DATABASE=%s;UID=%s;PWD=%s" % (DRIVER, HOST, DB, USER, password),
    timeout=15, readonly=True)
del password
cn.timeout = 15
cur = cn.cursor()

book = {}
for i in range(0, len(book_nos), 80):
    batch = book_nos[i:i + 80]
    marks = ",".join("?" * len(batch))
    for doc_no, lines, invoiced in cur.execute(
            f"""SELECT h.DocNo, COUNT(DISTINCT d.DtlKey),
                       COUNT(DISTINCT CASE WHEN iv.Cancelled = 'F' THEN d.DtlKey END)
                  FROM DO h WITH (NOLOCK)
                  JOIN DODTL d WITH (NOLOCK) ON d.DocKey = h.DocKey
                  LEFT JOIN DocTransfer t WITH (NOLOCK) ON t.FromDocDtlKey = d.DtlKey AND t.FromDocType = 'DO' AND t.ToDocType = 'IV'
                  LEFT JOIN IVDTL id WITH (NOLOCK) ON id.DtlKey = t.ToDocDtlKey
                  LEFT JOIN IV iv WITH (NOLOCK) ON iv.DocKey = id.DocKey
                 WHERE h.DocNo IN ({marks})
                 GROUP BY h.DocNo""", *batch).fetchall():
        book[doc_no] = {"lines": int(lines), "invoiced": int(invoiced)}
cn.close()

allowed, held = [], {}
for d in deliveries:
    b = book.get(d.get("book_no") or "")
    reason = ("no AutoCount number" if not d.get("book_no")
              else "not in the book" if b is None
              else "no lines in the book" if b["lines"] == 0
              else "invoiced in AutoCount" if b["invoiced"] > 0
              else None)
    if reason:
        held.setdefault(reason, []).append(d["do_number"])
    else:
        allowed.append(d["do_number"])

allowed = sorted(set(allowed))
if any(not re.fullmatch(r"HC-DO-[0-9A-Z-]+", n) for n in allowed):
    sys.exit("REFUSING: a delivery number does not have the migrated HC-DO- shape")

cut = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
dest = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "scm", "lib",
                    "migrated-deliveries-not-invoiced.generated.ts")
with open(dest, "w", encoding="utf-8", newline="\n") as fh:
    fh.write("// GENERATED by backend/scripts/export-migrated-deliveries-not-invoiced.py - do not edit by hand.\n")
    fh.write("//\n")
    fh.write("// The delivery orders carried over from AutoCount that AutoCount never\n")
    fh.write("// invoiced, measured against the live book (docs/bugs/0918). Such a delivery is\n")
    fh.write("// invoiced in the ERP like any other; every other migrated delivery is still\n")
    fh.write("// refused by the invoice paths (lib/si-from-do.ts, lib/migrated-chain.ts).\n")
    fh.write(f"// Book read {cut}; ERP list {erp['listedAt']}; company {erp['companyId']}.\n")
    for reason, nos in sorted(held.items()):
        fh.write(f"// Held, {reason}: {len(nos)}.\n")
    fh.write("\n")
    fh.write(f"export const MIGRATED_DELIVERIES_NOT_INVOICED_AS_OF = '{cut}';\n\n")
    fh.write("export const MIGRATED_DELIVERIES_NOT_INVOICED_IN_AUTOCOUNT: ReadonlySet<string> = new Set([\n")
    for n in allowed:
        fh.write(f"  '{n}',\n")
    fh.write("]);\n")

print(f"wrote {os.path.normpath(dest)}")
print(f"migrated deliveries: {len(deliveries)}; never invoiced in AutoCount: {len(allowed)}")
for reason, nos in sorted(held.items()):
    print(f"  held, {reason}: {len(nos)} {nos[:10]}")
