// Resolve any venue label (PMS or v8) to one of the 87 canonical PMS venues.
const fs = require("fs");
const CANON = fs.readFileSync("pms_venues.txt", "utf8").split(/\r?\n/).filter(Boolean);

// Explicit aliases: regex (tested on the UPPERCASED raw label) -> canonical PMS venue name.
// Order matters: more specific first. These cover abbreviations that don't token-match.
const ALIAS = [
  [/\bMVEC\b.*SOUTHKEY|SOUTHKEY.*MIDVALLEY|MIDVALLEY.*SOUTHKEY|JB.*MIDVALLEY|MIDVALLEY.*\bJB\b|JB MIDVALLEY|MID VALLEY SOUTHKEY|MVEC SOUHTKEY|MVEC SOUTHKEY/, "MVEC SOUTHKEY"],
  [/\bMID ?VALLEY\b|MVEC\b|MVEC KL|MVEC MID VALLEY|MID VALLEY EXHIBITION|MIDVALLEY BEDDING/, "MID VALLEY"], // KL Mid Valley (after Southkey ruled out)
  [/\bSCCC\b|SETIA CITY/, "SETIA CITY CONVENTION CENTRE"],
  [/\bSSCC\b|SETIA SPICE|SPICE SSCC|SPICE ARENA SSCC/, "SETIA SPICE CONVENTION CENTRE"],
  [/PISA|SPICE ARENA|^SPICE$|\bSPICE\b/, "PISA SPICE ARENA CONVENTION CENTRE"], // generic SPICE arena (Penang) after Setia Spice
  [/\bMITEC\b|MALAYSIA INTERNATIONAL TRADE AND EXHIBITION/, "MALAYSIA INTERNATIONAL TRADE AND EXHIBITION CENTRE"], // KL — must precede MELAKA MITC rule
  [/\bMITC\b|MALACCA.*(MITC|INTERNATIONAL TRADE)|MELAKA INTERNATIONAL TRADE|^MALACCA$/, "MELAKA INTERNATIONAL TRADE CENTRE"],
  [/\bKLCC\b|KUALA LUMPUR CONVENTION/, "KUALA LUMPUR CONVENTION CENTRE"],
  [/\bWTC\b|WORLD TRADE CENTRE/, "WORLD TRADE CENTRE KUALA LUMPUR"],
  [/STADIUM.*(BUKIT|BKT) JALIL|(BUKIT|BKT) JALIL STADIUM|^BUKIT JALIL$/, "STADIUM BUKIT JALIL"],
  [/PAV(ILION|ILLION|)\b.*(BUKIT|BKT|BUKTI) JALIL|PEX PAVILION|PAV BJ|PAVILLION BJ|\bPAV BJ\b/, "PAVILION BUKIT JALIL"],
  [/STADIUM.*(INDERA|ENDERA) MULIA|(INDERA|ENDERA) MULIA/, "STADIUM INDERA MULIA"],
  [/SPCC SUNWAY PUTRA|SUNWAY PUTRA/, "SUNWAY PYRAMID CONVENTION CENTRE"], // note: verify — Sunway Putra vs Pyramid
  [/SUNWAY PYRAMID|SPCC SUNWAY PYRAMID|SUNWAY PYRAMID CONVERSION|SUNWAY SPCC|^SPCC$/, "SUNWAY PYRAMID CONVENTION CENTRE"],
  [/SUNWAY CARNIVAL/, "SUNWAY CARNIVAL"],
  [/SUNWAY KLUANG/, "SUNWAY KLUANG MALL"],
  [/\bICCC\b|IPOH CONVENTION|\bICC\b/, "IPOH CONVENTION CENTRE"],
  [/\bKLBEC\b|KL BASE EXHIBITION/, "KL BASE EXHIBITION CENTER"],
  [/IOIGECC|IOI GECC/, "IOIGECC"],
  [/IOI (CITY )?MALL PUTRAJAYA|IOI PUTRAJAYA/, "IOI MALL PUTRAJAYA"],
  [/IOI (DAMANSARA|MALL DAMANSARA)/, "IOI MALL DAMANSARA"],
  [/IOI KULAI|IOI MALL KULAI/, "IOI MALL KULAI"],
  [/AICC|AUSTIN.*(CONVENTION|INTERNATIONAL)|AUSTIN JOHOR/, "AUSTIN INTERNATIONAL CONVENTION CENTRE"],
  [/PERSADA JOHOR|JB PERSADA/, "PERSADA JOHOR INTERNATIONAL CONVENTION CENTRE"],
  [/\bPICCA\b|PENANG INTERNATIONAL CONVENTION|BUTTERWORTH ARENA|\bBUTTERWORTH\b|SEBERANG PERAI ARENA|SP ARENA/, "PENANG INTERNATIONAL CONVENTION CULTURAL AND ARTS CENTRE"],
  [/\bPWCC\b|PENANG WATERFRONT/, "PENANG WATERFRONT CONVENTION CENTRE"],
  [/\bBCCK\b|BORNEO CONVENTION|KUCHING.*BCCK/, "BORNEO CONVENTION CENTRE KUCHING"],
  [/\bMCCC?\b|KUCHING METROCITY|METROCITY/, "KUCHING METROCITY CONVENTION CENTRE"],
  [/\bITCC\b|INTERNATIONAL TECHNOLOGY AND COMMERCIAL/, "INTERNATIONAL TECHNOLOGY AND COMMERCIAL CENTRE"],
  [/\bSICC\b|SABAH INTERNATIONAL CONVENTION/, "SABAH INTERNATIONAL CONVENTION CENTRE"],
  [/SURIA SABAH/, "SURIA SABAH"],
  [/CENTRE POINT|CENTREPOINT/, "CENTRE POINT"],
  [/SULTAN AHMAD SHAH|SASCC/, "SULTAN AHMAD SHAH CONVENTION CENTRE"],
  [/DATARAN CENTRIO|CENTRIO/, "DATARAN CENTRIO"],
  [/DATARAN PAHLAWAN|PAHLAWAN/, "DATARAN PAHLAWAN MELAKA MEGAMALL"],
  [/MAHKOTA PARADE/, "MAHKOTA PARADE"],
  [/AMAN CENTRAL|AMANCENTRAL/, "AMAN CENTRAL"],
  [/AMANJAYA/, "AMANJAYA MALL SUNGAI PETANI"],
  [/THE STARLING|STARLING/, "THE STARLING MALL"],
  [/STRAIT[S]? QUAY/, "STRAITS QUAY"],
  [/GURNEY PARAGON/, "GURNEY PARAGON"],
  [/EAST COAST MALL/, "EAST COAST MALL"],
  [/KUANTAN CITY/, "KUANTAN CITY MALL"],
  [/NU EMPIRE|EMPIRE SUBANG/, "NU EMPIRE SUBANG"],
  [/DESA ?PARK/, "DESA PARK CITY"],
  [/3 ?DAMANSARA/, "3 DAMANSARA"],
  [/1 MONT KIARA|MONT KIARA/, "1 MONT KIARA MALL"],
  [/EKO CHERAS/, "EKO CHERAS MALL"],
  [/AEON CHERAS/, "AEON CHERAS SELATAN"],
  [/AVENUE K/, "AVENUE K"],
  [/KL GATEWAY/, "KL GATEWAY MALL"],
  [/BLOOMSVALE/, "BLOOMSVALE"],
  [/MELAWATI/, "MELAWATI MALL"],
  [/KSL CITY/, "KSL CITY MALL"],
  [/KSL ESPLANADE/, "KSL ESPLANADE MALL"],
  [/PARADIGM/, "PARADIGM MALL"],
  [/SUTERA MALL|JOHOR SUTERA|SUTERA SOLO/, "SUTERA MALL"],
  [/SUTERA SQUARE/, "SUTERA SQUARE"],
  [/THE COMMUNE|COMMUNE KULAI/, "THE COMMUNE KULAI"],
  [/AEON TEBRAU|AEON TERBAU|AEON TERBRAU/, "AEON TEBRAU CITY"],
  [/AEON PERMAS/, "AEON PERMAS JAYA"],
  [/AEON KINTA/, "AEON KINTA CITY"],
  [/AEON STATION 18/, "AEON STATION 18"],
  [/AEON SEREMBAN/, "AEON SEREMBAN 2"],
  [/AEON SERI MANJUNG/, "AEON SERI MANJUNG"],
  [/AEON TAIPING/, "AEON TAIPING"],
  [/AEON TAMAN EQUINE|AEON TMN EQUINE/, "AEON TAMAN EQUINE"],
  [/AEON RAWANG/, "AEON RAWANG"],
  [/AEON NILAI|AEON MALL NILAI/, "AEON NILAI"],
  [/AEON METRO PRIMA|METRO PRIMA KEPONG/, "AEON METRO PRIMA KEPONG"],
  [/AEON BIG KEPONG/, "AEON BIG KEPONG"],
  [/AEON BIG SUBANG/, "AEON BIG SUBANG"],
  [/AEON BIG WANGSA|WANGSA MAJU/, "AEON BIG WANGSA MAJU"],
  [/AEON BUKIT MERTAJAM|AEON ALMA BUKIT MERTAJAM/, "AEON BUKIT MERTAJAM"],
  [/AEON BUKIT RAJA/, "AEON BUKIT RAJA"],
  [/AEON AU2|AU2 SETIAWANGSA/, "AEON AU2 SETIAWANGSA"],
  [/AEON KUCHING/, "AEON KUCHING"],
  [/AEON MAHKOTA/, "MAHKOTA PARADE"],
  [/PALM MALL/, "PALM MALL"],
  [/MESA MALL/, "MESA MALL"],
  [/KB MALL/, "KB MALL"],
  [/KTCC/, "KTCC MALL"],
  [/DEWAN MILLEN|KEPALA BATAS/, "DEWAN MILLENNIUM KEPALA BATAS"],
  [/BOULEVARD.*MIRI|MIRI/, "BOULEVARD SHOPPING MALL MIRI"],
  [/VIVACITY/, "VIVACITY MEGAMALL"],
  [/SUNSHINE (PENANG|CENTRAL)/, "SUNSHINE CENTRAL"],
  [/AUTO CITY/, "AUTO CITY"],
  [/TROPICANA GARDENS/, "TROPICANA GARDENS MALL"],
  [/ALAMANDA/, "ALAMANDA PUTRAJAYA"],
  [/AVENUE K/, "AVENUE K"],
];

function canon(raw) {
  const U = String(raw || "").toUpperCase().replace(/[.,]/g, " ").replace(/\s+/g, " ").trim();
  if (!U) return null;
  for (const [re, name] of ALIAS) if (re.test(U)) return name;
  // token fallback vs the 87
  const toks = (s) => new Set(String(s).toUpperCase().replace(/\b(THE|MALL|CONVENTION|CENTRE|CENTER|CITY|SHOPPING|SOLO|KL|PG|JB|JHB|PNG)\b/g, "").replace(/[^A-Z0-9 ]/g, "").split(/\s+/).filter((w) => w.length > 2));
  const ut = toks(U);
  let best = null, bs = 0;
  for (const c of CANON) { const ct = toks(c); let m = 0; ut.forEach((w) => { if (ct.has(w)) m++; }); const sc = m / Math.max(ct.size, 1); if (sc > bs) { bs = sc; best = c; } }
  return bs >= 0.5 ? best : null;
}

module.exports = { canon, CANON };

if (require.main === module) {
  const v8 = fs.readFileSync("v8_venues.txt", "utf8").split(/\r?\n/).filter(Boolean);
  const unresolved = v8.filter((v) => !canon(v));
  console.log(`v8 labels: ${v8.length} | resolved: ${v8.length - unresolved.length} | UNRESOLVED: ${unresolved.length}`);
  unresolved.forEach((v) => console.log(`  ??  ${v}`));
  // sanity: show the tricky disambiguations
  console.log("\nspot-check:");
  ["SCCC SHAH ALAM", "SSCC SPICE PG", "SPICE ARENA PG", "MITC MELAKA", "KLCC", "MVEC SOUTHKEY JB", "MIDVALLEY KL", "MID VALLEY, KL", "STADIUM BUKIT JALIL", "PAVILION BUKIT JALIL", "SPCC SUNWAY PUTRA KL"].forEach((x) => console.log(`  "${x}" -> ${canon(x)}`));
}
