-- 20260908T1501_share_export_log.sql
--
-- WHAT THIS CHANGES, and why it is safe to run against production:
--   Creates `share_export_log` — one row per Excel export taken through a
--   public calendar share link (owner 2026-09-08, brand safeguards: "log which
--   brand exported and when, for accountability"). Append-only; nothing reads
--   it on a request path. `kind` is 'contractor' | 'brand', `subject` is the
--   contractor or brand NAME the token resolved to, `token` is the link used,
--   `ip` the caller as the rate limiter sees it, `row_count` what left the
--   server. Additive + idempotent.
--
-- REVERSAL: DROP TABLE IF EXISTS share_export_log;
-- Verified against: not yet executed against prod — deploy.yml applies it on merge; the DDL uses only types already present in `public` (text, bigint, integer, to_char default as in 20260903T1237).

CREATE TABLE IF NOT EXISTS share_export_log (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind        text NOT NULL,
  subject     text NOT NULL,
  token       text NOT NULL,
  ip          text,
  row_count   integer NOT NULL DEFAULT 0,
  created_at  text DEFAULT to_char(timezone('UTC'::text, now()), 'YYYY-MM-DD"T"HH24:MI:SS"Z"'::text)
);

CREATE INDEX IF NOT EXISTS idx_share_export_log_subject
  ON share_export_log(kind, subject, created_at);
