// GENERATED by backend/scripts/export-migrated-receipts-not-invoiced.py - do not edit by hand.
//
// The goods receipts (GRNs) carried over from AutoCount that AutoCount never
// invoiced, measured against the live book (docs/bugs/0918, purchase-side
// mirror). Such a GRN is billed into a purchase invoice in the ERP like any
// other; every other migrated GRN is still refused by the invoice paths
// (routes/purchase-invoices.ts, lib/migrated-chain.ts).
//
// SHIPPED EMPTY: the office has not run the measurement yet, so the feature is
// INERT — no migrated GRN is unblocked and behaviour is unchanged. To activate
// it, run scripts/list-migrated-receipts.mjs then
// scripts/export-migrated-receipts-not-invoiced.py against the AutoCount book,
// which rewrites this file with the real numbers (the same one-time step the
// sales side did on 2026-09-15).

export const MIGRATED_RECEIPTS_NOT_INVOICED_AS_OF = 'not-yet-measured';

export const MIGRATED_RECEIPTS_NOT_INVOICED_IN_AUTOCOUNT: ReadonlySet<string> = new Set([
]);
